/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1ProjectUploadSessionUidBatchUploadProjectTypeDataTests
    {
        // TODO uncomment below to declare an instance variable for ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData
        //private ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData
            //instance = new ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData
        /// </summary>
        [Test]
        public void ApiV1ProjectUploadSessionUidBatchUploadProjectTypeDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData
            //Assert.IsInstanceOf(typeof(ApiV1ProjectUploadSessionUidBatchUploadProjectTypeData), instance);
        }


        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
