/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ApiV1ProjectUploadSessionUidBatchUploadCreatedBy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1ProjectUploadSessionUidBatchUploadCreatedByTests
    {
        // TODO uncomment below to declare an instance variable for ApiV1ProjectUploadSessionUidBatchUploadCreatedBy
        //private ApiV1ProjectUploadSessionUidBatchUploadCreatedBy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiV1ProjectUploadSessionUidBatchUploadCreatedBy
            //instance = new ApiV1ProjectUploadSessionUidBatchUploadCreatedBy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiV1ProjectUploadSessionUidBatchUploadCreatedBy
        /// </summary>
        [Test]
        public void ApiV1ProjectUploadSessionUidBatchUploadCreatedByInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ApiV1ProjectUploadSessionUidBatchUploadCreatedBy
            //Assert.IsInstanceOf(typeof(ApiV1ProjectUploadSessionUidBatchUploadCreatedBy), instance);
        }


        /// <summary>
        /// Test the property 'Pk'
        /// </summary>
        [Test]
        public void PkTest()
        {
            // TODO unit test for the property 'Pk'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

    }

}
