/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject6
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject6Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject6
        //private InlineObject6 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject6
            //instance = new InlineObject6();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject6
        /// </summary>
        [Test]
        public void InlineObject6InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject6
            //Assert.IsInstanceOf(typeof(InlineObject6), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SendEmailNotification'
        /// </summary>
        [Test]
        public void SendEmailNotificationTest()
        {
            // TODO unit test for the property 'SendEmailNotification'
        }
        /// <summary>
        /// Test the property 'Owners'
        /// </summary>
        [Test]
        public void OwnersTest()
        {
            // TODO unit test for the property 'Owners'
        }
        /// <summary>
        /// Test the property 'Reviewers'
        /// </summary>
        [Test]
        public void ReviewersTest()
        {
            // TODO unit test for the property 'Reviewers'
        }
        /// <summary>
        /// Test the property 'SuperReviewers'
        /// </summary>
        [Test]
        public void SuperReviewersTest()
        {
            // TODO unit test for the property 'SuperReviewers'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'HideClauseReview'
        /// </summary>
        [Test]
        public void HideClauseReviewTest()
        {
            // TODO unit test for the property 'HideClauseReview'
        }

    }

}
