/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject58
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject58Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject58
        //private InlineObject58 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject58
            //instance = new InlineObject58();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject58
        /// </summary>
        [Test]
        public void InlineObject58InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject58
            //Assert.IsInstanceOf(typeof(InlineObject58), instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'LocationStart'
        /// </summary>
        [Test]
        public void LocationStartTest()
        {
            // TODO unit test for the property 'LocationStart'
        }
        /// <summary>
        /// Test the property 'LocationEnd'
        /// </summary>
        [Test]
        public void LocationEndTest()
        {
            // TODO unit test for the property 'LocationEnd'
        }
        /// <summary>
        /// Test the property 'LocationText'
        /// </summary>
        [Test]
        public void LocationTextTest()
        {
            // TODO unit test for the property 'LocationText'
        }
        /// <summary>
        /// Test the property 'AssigneeId'
        /// </summary>
        [Test]
        public void AssigneeIdTest()
        {
            // TODO unit test for the property 'AssigneeId'
        }
        /// <summary>
        /// Test the property 'AssignDate'
        /// </summary>
        [Test]
        public void AssignDateTest()
        {
            // TODO unit test for the property 'AssignDate'
        }
        /// <summary>
        /// Test the property 'StatusId'
        /// </summary>
        [Test]
        public void StatusIdTest()
        {
            // TODO unit test for the property 'StatusId'
        }

    }

}
