/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject51
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject51Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject51
        //private InlineObject51 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject51
            //instance = new InlineObject51();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject51
        /// </summary>
        [Test]
        public void InlineObject51InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject51
            //Assert.IsInstanceOf(typeof(InlineObject51), instance);
        }


        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Test]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Test]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'LocationStart'
        /// </summary>
        [Test]
        public void LocationStartTest()
        {
            // TODO unit test for the property 'LocationStart'
        }
        /// <summary>
        /// Test the property 'LocationEnd'
        /// </summary>
        [Test]
        public void LocationEndTest()
        {
            // TODO unit test for the property 'LocationEnd'
        }
        /// <summary>
        /// Test the property 'LocationText'
        /// </summary>
        [Test]
        public void LocationTextTest()
        {
            // TODO unit test for the property 'LocationText'
        }
        /// <summary>
        /// Test the property 'ModifiedBy'
        /// </summary>
        [Test]
        public void ModifiedByTest()
        {
            // TODO unit test for the property 'ModifiedBy'
        }

    }

}
