/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject45
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject45Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject45
        //private InlineObject45 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject45
            //instance = new InlineObject45();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject45
        /// </summary>
        [Test]
        public void InlineObject45InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject45
            //Assert.IsInstanceOf(typeof(InlineObject45), instance);
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'ExcludeRegexps'
        /// </summary>
        [Test]
        public void ExcludeRegexpsTest()
        {
            // TODO unit test for the property 'ExcludeRegexps'
        }
        /// <summary>
        /// Test the property 'DefinitionWords'
        /// </summary>
        [Test]
        public void DefinitionWordsTest()
        {
            // TODO unit test for the property 'DefinitionWords'
        }
        /// <summary>
        /// Test the property 'IncludeRegexps'
        /// </summary>
        [Test]
        public void IncludeRegexpsTest()
        {
            // TODO unit test for the property 'IncludeRegexps'
        }
        /// <summary>
        /// Test the property 'RegexpsPreProcessLower'
        /// </summary>
        [Test]
        public void RegexpsPreProcessLowerTest()
        {
            // TODO unit test for the property 'RegexpsPreProcessLower'
        }
        /// <summary>
        /// Test the property 'DetectedValue'
        /// </summary>
        [Test]
        public void DetectedValueTest()
        {
            // TODO unit test for the property 'DetectedValue'
        }
        /// <summary>
        /// Test the property 'ExtractionHint'
        /// </summary>
        [Test]
        public void ExtractionHintTest()
        {
            // TODO unit test for the property 'ExtractionHint'
        }
        /// <summary>
        /// Test the property 'TextPart'
        /// </summary>
        [Test]
        public void TextPartTest()
        {
            // TODO unit test for the property 'TextPart'
        }
        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Test]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

    }

}
