/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject72
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject72Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject72
        //private InlineObject72 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject72
            //instance = new InlineObject72();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject72
        /// </summary>
        [Test]
        public void InlineObject72InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject72
            //Assert.IsInstanceOf(typeof(InlineObject72), instance);
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Password1'
        /// </summary>
        [Test]
        public void Password1Test()
        {
            // TODO unit test for the property 'Password1'
        }
        /// <summary>
        /// Test the property 'Password2'
        /// </summary>
        [Test]
        public void Password2Test()
        {
            // TODO unit test for the property 'Password2'
        }

    }

}
