/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject101
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject101Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject101
        //private InlineObject101 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject101
            //instance = new InlineObject101();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject101
        /// </summary>
        [Test]
        public void InlineObject101InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject101
            //Assert.IsInstanceOf(typeof(InlineObject101), instance);
        }


        /// <summary>
        /// Test the property 'Fixture'
        /// </summary>
        [Test]
        public void FixtureTest()
        {
            // TODO unit test for the property 'Fixture'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Test]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }

    }

}
