/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject33
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject33Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject33
        //private InlineObject33 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject33
            //instance = new InlineObject33();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject33
        /// </summary>
        [Test]
        public void InlineObject33InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject33
            //Assert.IsInstanceOf(typeof(InlineObject33), instance);
        }


        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'LocationStart'
        /// </summary>
        [Test]
        public void LocationStartTest()
        {
            // TODO unit test for the property 'LocationStart'
        }
        /// <summary>
        /// Test the property 'LocationEnd'
        /// </summary>
        [Test]
        public void LocationEndTest()
        {
            // TODO unit test for the property 'LocationEnd'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'FieldValueId'
        /// </summary>
        [Test]
        public void FieldValueIdTest()
        {
            // TODO unit test for the property 'FieldValueId'
        }
        /// <summary>
        /// Test the property 'FieldId'
        /// </summary>
        [Test]
        public void FieldIdTest()
        {
            // TODO unit test for the property 'FieldId'
        }

    }

}
