/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject84
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject84Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject84
        //private InlineObject84 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject84
            //instance = new InlineObject84();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject84
        /// </summary>
        [Test]
        public void InlineObject84InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject84
            //Assert.IsInstanceOf(typeof(InlineObject84), instance);
        }


        /// <summary>
        /// Test the property 'StatusId'
        /// </summary>
        [Test]
        public void StatusIdTest()
        {
            // TODO unit test for the property 'StatusId'
        }
        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Test]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }
        /// <summary>
        /// Test the property 'DocumentIds'
        /// </summary>
        [Test]
        public void DocumentIdsTest()
        {
            // TODO unit test for the property 'DocumentIds'
        }
        /// <summary>
        /// Test the property 'NoDocumentIds'
        /// </summary>
        [Test]
        public void NoDocumentIdsTest()
        {
            // TODO unit test for the property 'NoDocumentIds'
        }

    }

}
