/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject76
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject76Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject76
        //private InlineObject76 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject76
            //instance = new InlineObject76();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject76
        /// </summary>
        [Test]
        public void InlineObject76InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject76
            //Assert.IsInstanceOf(typeof(InlineObject76), instance);
        }


        /// <summary>
        /// Test the property 'AssigneeId'
        /// </summary>
        [Test]
        public void AssigneeIdTest()
        {
            // TODO unit test for the property 'AssigneeId'
        }
        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Test]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }
        /// <summary>
        /// Test the property 'AnnotationIds'
        /// </summary>
        [Test]
        public void AnnotationIdsTest()
        {
            // TODO unit test for the property 'AnnotationIds'
        }
        /// <summary>
        /// Test the property 'NoAnnotationIds'
        /// </summary>
        [Test]
        public void NoAnnotationIdsTest()
        {
            // TODO unit test for the property 'NoAnnotationIds'
        }

    }

}
