/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject69
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject69Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject69
        //private InlineObject69 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject69
            //instance = new InlineObject69();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject69
        /// </summary>
        [Test]
        public void InlineObject69InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject69
            //Assert.IsInstanceOf(typeof(InlineObject69), instance);
        }


        /// <summary>
        /// Test the property 'NewPassword1'
        /// </summary>
        [Test]
        public void NewPassword1Test()
        {
            // TODO unit test for the property 'NewPassword1'
        }
        /// <summary>
        /// Test the property 'NewPassword2'
        /// </summary>
        [Test]
        public void NewPassword2Test()
        {
            // TODO unit test for the property 'NewPassword2'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

    }

}
