/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject102
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject102Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject102
        //private InlineObject102 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject102
            //instance = new InlineObject102();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject102
        /// </summary>
        [Test]
        public void InlineObject102InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject102
            //Assert.IsInstanceOf(typeof(InlineObject102), instance);
        }


        /// <summary>
        /// Test the property 'QueryInfo'
        /// </summary>
        [Test]
        public void QueryInfoTest()
        {
            // TODO unit test for the property 'QueryInfo'
        }
        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Test]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

    }

}
