/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject10
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject10Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject10
        //private InlineObject10 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject10
            //instance = new InlineObject10();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject10
        /// </summary>
        [Test]
        public void InlineObject10InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject10
            //Assert.IsInstanceOf(typeof(InlineObject10), instance);
        }


        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Test]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }
        /// <summary>
        /// Test the property 'ClassValue'
        /// </summary>
        [Test]
        public void ClassValueTest()
        {
            // TODO unit test for the property 'ClassValue'
        }
        /// <summary>
        /// Test the property 'TextUnitId'
        /// </summary>
        [Test]
        public void TextUnitIdTest()
        {
            // TODO unit test for the property 'TextUnitId'
        }

    }

}
