/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject85
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject85Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject85
        //private InlineObject85 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject85
            //instance = new InlineObject85();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject85
        /// </summary>
        [Test]
        public void InlineObject85InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject85
            //Assert.IsInstanceOf(typeof(InlineObject85), instance);
        }


        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Test]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }
        /// <summary>
        /// Test the property 'RemoveAll'
        /// </summary>
        [Test]
        public void RemoveAllTest()
        {
            // TODO unit test for the property 'RemoveAll'
        }
        /// <summary>
        /// Test the property 'ExcludeDocumentIds'
        /// </summary>
        [Test]
        public void ExcludeDocumentIdsTest()
        {
            // TODO unit test for the property 'ExcludeDocumentIds'
        }

    }

}
