/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject88
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject88Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject88
        //private InlineObject88 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject88
            //instance = new InlineObject88();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject88
        /// </summary>
        [Test]
        public void InlineObject88InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject88
            //Assert.IsInstanceOf(typeof(InlineObject88), instance);
        }


        /// <summary>
        /// Test the property 'NClusters'
        /// </summary>
        [Test]
        public void NClustersTest()
        {
            // TODO unit test for the property 'NClusters'
        }
        /// <summary>
        /// Test the property 'Force'
        /// </summary>
        [Test]
        public void ForceTest()
        {
            // TODO unit test for the property 'Force'
        }
        /// <summary>
        /// Test the property 'ClusterBy'
        /// </summary>
        [Test]
        public void ClusterByTest()
        {
            // TODO unit test for the property 'ClusterBy'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

    }

}
