/* 
 * Contraxsuite API
 *
 * Contraxsuite API
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InlineObject75
    /// </summary>
    [DataContract]
    public partial class InlineObject75 :  IEquatable<InlineObject75>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject75" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineObject75() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject75" /> class.
        /// </summary>
        /// <param name="projectIds">projectIds (required).</param>
        public InlineObject75(List<int> projectIds = default(List<int>))
        {
            // to ensure "projectIds" is required (not null)
            if (projectIds == null)
            {
                throw new InvalidDataException("projectIds is a required property for InlineObject75 and cannot be null");
            }
            else
            {
                this.ProjectIds = projectIds;
            }
            
        }
        
        /// <summary>
        /// Gets or Sets ProjectIds
        /// </summary>
        [DataMember(Name="project_ids", EmitDefaultValue=true)]
        public List<int> ProjectIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject75 {\n");
            sb.Append("  ProjectIds: ").Append(ProjectIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineObject75);
        }

        /// <summary>
        /// Returns true if InlineObject75 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineObject75 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject75 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProjectIds == input.ProjectIds ||
                    this.ProjectIds != null &&
                    input.ProjectIds != null &&
                    this.ProjectIds.SequenceEqual(input.ProjectIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProjectIds != null)
                    hashCode = hashCode * 59 + this.ProjectIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
